### ISSUE TITLE
SIGSEGV when missing `pmm:` block in PerconaPGCluster CR

### ISSUE THREAD

**Issue by alexfouche** [percona/percona-postgresql-operator#588]
If the `pmm:` block is missing from the PerconaPGCluster CR, then the Postgres Operator crashes with the following error.

If the `pmm:` is there either enabled or disabled, no problem

```
time="2023-11-28T09:11:23Z" level=info msg="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" PerconaPGCluster=postgres/analytics controller=perconapgcluster controllerGroup=pgv2.percona.com controllerKind=PerconaPGCluster name=analytics namespace=postgres reconcileID=e73c9baa-e2c2-4842-bd42-f24fbf9c7a45 version=
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17a488c]

goroutine 451 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1a313a0, 0x2d59990})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/percona/percona-postgresql-operator/percona/controller/pgcluster.(*PGClusterReconciler).Reconcile.func1()
	/go/src/github.com/percona/percona-postgresql-operator/percona/controller/pgcluster/controller.go:204 +0x9ac
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc0018b4400?, {{0xc001a012b0?, 0x0?}, {0xc001a012a0?, 0x1fdff58?}}, {0x1ff4d10, 0xc0018b4400})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x1fdff58, 0xc0011b5f20}, {0x1fe8a18, 0xc00069eae0}, {0x1ff4d10?, 0xc0018b4400}, 0xc001a012b0?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:211 +0x274
github.com/percona/percona-postgresql-operator/percona/controller/pgcluster.(*PGClusterReconciler).Reconcile(0xc0000c84d0, {0x1fdff58, 0xc0011b5f20}, {{{0xc001a012b0?, 0x0?}, {0xc001a012a0?, 0x40de87?}}})
	/go/src/github.com/percona/percona-postgresql-operator/percona/controller/pgcluster/controller.go:155 +0x54a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1fdff58?, {0x1fdff58?, 0xc0011b5f20?}, {{{0xc001a012b0?, 0x199a0e0?}, {0xc001a012a0?, 0x40f946?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000438f00, {0x1fdfeb0, 0xc00018e4b0}, {0x1ac82a0?, 0xc001dac680?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000438f00, {0x1fdfeb0, 0xc00018e4b0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```

The situation is recoverable by reapplying the CR with a `pmm:` block even in disabled, and restarting the Operator pod in Kubernetes

**Comment by alexfouche** [comment]
Duplicate #526
